### PR TITLE
Allow implementations to support a custom comparison function.

### PR DESCRIPTION
**Pull request by DUOLabs333**

### CODE REVIEW

**Comment by willscott** [comment]
Won't `fs` and `fs2` here always be string slices? rather than making a method for the handle to implement, can we put the comparison logic directly here?

e.g. https://pkg.go.dev/slices#Equal

**Comment by willscott** [comment]
would it be okay to check if `fs.Stat('/')` ==  `fs2.Stat('/')` as a way of seeing if they're the same filesystem?

**Comment by willscott** [comment]
would https://github.com/willscott/go-nfs/commit/828ed7258b6437875753ef7c0653aa3b4f6bc600 be sufficient? - i guess maybe would also be worthwhile to compare that the `billy.Capabilities()` of the two filesystems are the same

**Comment by DUOLabs333** [comment]
Now I get `comparing uncomparable type main.OverlayStat` (this is because in order to fix some inode validation issue with my implementation, I have to add the filesystem as an attribute).

**Comment by willscott** [comment]
I'm okay doing this with https://github.com/willscott/go-nfs/commit/c33eb6b50fdbd566f33347c894a9b37004dfc0cb

**Comment by DUOLabs333** [comment]
Can we use DeepEqual on fs and fs2 directly? Alternatively, I was thinking that we can compare the pointer values of the two filesystems.

**Comment by willscott** [comment]
> Can we use DeepEqual on fs and fs2 directly?

yes, that was my intention of what I was showing - the commit diff is confusing. https://github.com/willscott/go-nfs/compare/fix/onrename-fs is better

**Comment by DUOLabs333** [comment]
Ok, with the commit, Rename no longer crashes (it doesn't look like it returns the wrong thing).

**Comment by willscott** [comment]
closed in favor of #114

**Pull request closed without merging**
