### PR TITLE
Fixup/renameinvalidate

### PR DESCRIPTION
**Pull request by willscott**
simplify to remove inverse cache and directly invalidate handles

### CODE REVIEW

**Comment by DUOLabs333** [comment]
This doesn't fix the problem of handles not being one-to-one/a new handle is returned every lookup.

**Comment by willscott** [comment]
Good point. I think we do need the complexity you suggested. I added an additional method to properly evict from the reverse index as well.

**Comment by DUOLabs333** [comment]
Technically, the reverse cache must also hold the filesystems --- at which point, we should just use my PR.

**Comment by willscott** [comment]
does it?
* if the handle matches, you can recover the filesystem from the forward cache
* I'd prefer a single strong type rather than `any` for the value
* we should be doing expiry so that the reverse cache doesn't grow in an unbounded way

**Pull request merged**
